version: "3.7"

services:
    backend:
        build:
            context: ./backend # Tylko katalog backend
            dockerfile: Dockerfile
        env_file:
            - ./backend/.env
        ports:
            - "8000:8000"

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "5173:5173"
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./frontend:/app
            - /app/node_modules

volumes:
    static:
    frontend:

