name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        
    - name: Install pnpm
      run: npm install -g pnpm

    - name: Add pnpm to PATH
      run: echo "::add-path::$(npm root -g)/pnpm"

    - name: Install dependencies with pnpm
      working-directory: ./frontend
      run: pnpm install

    - name: Build with pnpm
      working-directory: ./frontend
      run: pnpm run build --if-present

    - name: Run tests with pnpm
      working-directory: ./frontend
      run: pnpm test
